# Generated by Django 5.0.2 on 2024-02-23 14:45

import account.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', account.managers.UserManager()),
            ],
        ),
    ]
